spring.application.name=card-api

# DB ?? ??
spring.datasource.url=jdbc:mysql://localhost:3307/damoa?serverTimezone=Asia/Seoul
spring.datasource.username=root
spring.datasource.password=1234
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA/Hibernate ??
# 1. ?? ?? ? ???? ?? ?? ?? (data.sql ??? ??)
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true

# SQL ??? ??
# 2. data.sql ??? ?? ????? ??
spring.sql.init.mode=always
# 3. Hibernate? ??? ??? ?? ?? data.sql? ????? ????
spring.jpa.defer-datasource-initialization=true

# (??) SQL ??? ?? ??? ?? ??? ? (????)
spring.sql.init.continue-on-error=true